spring.application.name=RedisIntegration


# Enable Swagger UI
springdoc.swagger-ui.enabled=true

# Path where Swagger UI will be available
springdoc.swagger-ui.path=/swagger-ui.html

# Path for OpenAPI documentation
springdoc.api-docs.path=/v3/api-docs

# Sort APIs alphabetically
springdoc.swagger-ui.operationsSorter=alpha

# Sort tags alphabetically
springdoc.swagger-ui.tagsSorter=alpha

# Show request duration in Swagger UI
springdoc.swagger-ui.display-request-duration=true